parameters:
    # Default Redis keys prefix
    build-version: '0000000000000000'
    env(ELASTIC_SEARCH_INDEX_PREFIX): ''

    env(IGNORE_DEFAULT_ADMIN_PASSWORD_CHECK): '0'
    env(MAILER_FORCE_WHITELIST): 0
    env(REDIS_PREFIX): ''

    # Seed for demo data generation
    faker.seed: 1234

    # Time zone that the admin use for entering and viewing dates and times in the datetime pickers
    shopsys.admin_display_timezone: ~

    # Locales to select from in the administration. The first locale is the default one. All locales must be registered in domains.yaml
    shopsys.allowed_admin_locales: ['en', 'cs']

    # Hours defined in cron.yaml correspond to this timezone (default is PHP timezone)
    shopsys.cron_timezone: ~

    shopsys.display_cron_overview_for_superadmin_only: false

    # Default extended classes mapping
    shopsys.entity_extension.map: {}
