ChangePersonalDataInputDecorator:
    type: input-object
    decorator: true
    inherits:
        - 'NameInputObjectDecorator'
        - 'TelephoneInputObjectDecorator'
    config:
        fields:
            newsletterSubscription:
                type: "Boolean!"
                description: "Whether customer user should receive newsletters or not"
