shopsys_administration:
    prefix: /%admin_url%
    resource: "@ShopsysAdministrationBundle/Controller"
    type: attribute

shopsys_framework:
    prefix: /%admin_url%
    resource: "@ShopsysFrameworkBundle/Controller/Admin"
    type: attribute
