AvailabilityDecorator:
    type: object
    decorator: true
    config:
        description: "Represents an availability"
        fields:
            name:
                type: "String!"
                description: "Localized availability name (domain dependent)"
            status:
                type: "AvailabilityStatusEnum!"
                description: "Availability status in a format suitable for usage in the code"
