CartItemModificationsResultDecorator:
    type: object
    decorator: true
    config:
        fields:
            noLongerListableCartItems:
                type: "[CartItem!]!"
            cartItemsWithModifiedPrice:
                type: "[CartItem!]!"
