CustomerUserQuery:
    type: object
    config:
        fields:
            CompanyCustomerUser:
                type: 'CompanyCustomerUser'
            RegularCustomerUser:
                type: 'RegularCustomerUser'
            currentCustomerUser:
                type: 'CustomerUser'
                resolve: "@=query('nullableCurrentCustomerUserQuery')"
                description: "Returns currently logged in customer user"
