SliderItem:
    type: object
    config:
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String!"
                description: "Slider name"
            link:
                type: "String!"
                description: "Target link"
            extendedText:
                type: "String"
                description: "Text below slider"
            extendedTextLink:
                type: "String"
                description: "Target link of text below slider"
            gtmId:
                type: "String!"
                description: "GTM ID"
            gtmCreative:
                type: "String"
                description: "GTM creative"
            description:
                type: "String!"
                description: "Slider description"
            rgbBackgroundColor:
                type: "String"
                description: "RGB color code for the background of the slider description box"
            opacity:
                type: "Float"
                description: "Opacity level for the background color of the slider description box"
            images:
                type: "[Image!]!"
                description: "Slider item images"
                resolve: '@=query("imagesByEntityPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            mainImage:
                type: "Image!"
                description: "Slider item image by params"
                resolve: '@=query("mainImageByEntityPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
