SliderItem:
    type: object
    inherits:
        - 'SliderItemDecorator'
    config:
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            extendedText:
                type: "String"
                description: "Text below slider"
            extendedTextLink:
                type: "String"
                description: "Target link of text below slider"
            gtmId:
                type: "String!"
                description: "GTM ID"
            gtmCreative:
                type: "String"
                description: "GTM creative"
