SliderItemDecorator:
    type: object
    decorator: true
    config:
        fields:
            name:
                type: "String!"
                description: "Slider name"
            link:
                type: "String!"
                description: "Target link"
            description:
                type: "String"
                description: "Slider description"
            rgbBackgroundColor:
                type: "String!"
                description: "RGB color code for the background of the slider description box"
            opacity:
                type: "Float!"
                description: "Opacity level for the background color of the slider description box"
            images:
                type: "[Image!]!"
                description: "Slider item images"
                resolve: '@=query("imagesByEntityPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            mainImage:
                type: "Image!"
                description: "Slider item image by params"
                resolve: '@=query("mainImageByEntityPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
